# Generated by Django 5.2.7 on 2025-10-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casillero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
                ('numero', models.PositiveSmallIntegerField()),
                ('valor', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('area', 'numero')},
            },
        ),
    ]
